---
- name: remove preinstalled containerd
  zypper:
    name: containerd
    state: absent

- name: remove versionlock for containerd
  command: zypper removelock containerd.io
  args:
    warn: false
  ignore_errors: true
  register: command_result
  changed_when: |
    'command_result.stdout is regex(".*lock has been successfully removed.")'
  when:
    - versionlocklist is defined and versionlocklist.stdout is defined
    - "(
      'containerd.io' in versionlocklist.stdout and
      not 'Keep installed : containerd.io-' + containerd_version in versionlocklist.stdout
      )"

- name: install containerd.io package
  zypper:
    name: "{{ 'containerd.io=' + containerd_version }}"
    state: present
    update_cache: true
  register: result
  until: result is success
  retries: 15
  delay: 60

- name: add versionlock for containerd
  command: zypper addlock containerd.io
  args:
    warn: false
  register: command_result
  changed_when: |
    'command_result.stdout is regex(".*lock has been successfully added.*")'
