---
- name: start containerd
  service:
    name: containerd
    state: restarted

- name: load images
  import_tasks: load.yaml

- name: set images fact
  set_fact:
    pull_images: "{{
      kubernetes_images +
      containerd_images +
      control_plane_images +
      extra_images
    }}"

- name: set aws images
  set_fact:
    pull_images: "{{ pull_images + aws_images }}"
  when: packer_builder_type.startswith('amazon')

- name: pull images
  include_tasks: check-or-pull-images.yaml
  vars:
    image_name: "{{ item }}"
  loop: "{{ pull_images }}"
