---
- name: check if versionlock exists
  command: zypper locks -s
  register: versionlocklist
  args:
    warn: false
  ignore_errors: true
  changed_when: false

- name: Export versionlocklist
  set_fact:
    exportedversionlocklist: "{{ versionlocklist }}"
