---
- name: add epel gpg key
  rpm_key:
    state: present
    key: "{{ epel_centos_8_rpm_gpg_key }}"

- name: install epel-release
  yum:
    name: "{{ epel_centos_8_rpm }}"
    state: present

- name: find this kernel headers
  yum:
    list: "kernel-headers-{{ hostvars[inventory_hostname].ansible_kernel }}"
  register: pkgheaders

# If possible we use headers from the main OS repo for this kernel. When
# this comes back empty, the next step will implicitly install what is
# needed.
# TODO(tillt): There must be a more deterministic way.
- name: Install Kernel Header and Devel from OS repo for Current Kernel
  yum:
    name:
      - "kernel-headers-{{ hostvars[inventory_hostname].ansible_kernel }}"
      - "kernel-devel-{{ hostvars[inventory_hostname].ansible_kernel }}"
  when: pkgheaders.results|length > 0

# Install NVIDIA repository, driver and tools
- name: Add NVIDIA repository for CUDA drivers and tools
  yum_repository:
    name: cuda
    description: NVIDIA cuda repository
    enabled: true
    baseurl: "{{ nvidia_repo_baseurl }}"
    gpgkey: "{{ nvidia_repo_gpgkey }}"
    gpgcheck: true

- name: Install cuda drivers and tools
  dnf:
    enablerepo:
      - "codeready-builder-for-rhel-8-{{ ansible_architecture }}-rpms"
      - "rhel-8-for-{{ ansible_architecture }}-baseos-rpms"
      - "rhel-8-for-{{ ansible_architecture }}-appstream-rpms"
    name:
      - "{{ nvidia_cuda_package }}"
    state: present

# libnvidia-container
- name: Add libnvidia-container repository
  yum_repository:
    name: libnvidia-container
    description: NVIDIA cuda repository
    enabled: false
    baseurl: "{{ libnvidia_container_repo_rhel }}"
    gpgkey: "{{ libnvidia_container_repo_gpgkey }}"
    gpgcheck: true

- name: install libnvidia-container
  dnf:
    name: libnvidia-container1
    enablerepo: libnvidia-container
    state: present

- name: Add libnvidia-container-runtime repository
  yum_repository:
    name: nvidia-container-runtime
    description: NVIDIA cuda repository
    enabled: false
    baseurl: "{{ nvidia_container_runtime_repo_rhel }}"
    gpgkey: "{{ nvidia_container_runtime_repo_gpgkey }}"
    gpgcheck: true

- name: Install nvidia-container-tools
  dnf:
    name: libnvidia-container-tools
    enablerepo:
      - libnvidia-container
    state: present

- name: Install nvidia-container-runtime
  dnf:
    name: "{{ nvidia_container_runtime_package }}"
    enablerepo:
      - nvidia-container-runtime
    state: present
