---
- name: load loop modules
  command: modprobe -d / -a loop i2c_core ipmi_msghandler

- name: prepare loop modules
  command: echo -e "loop\ni2c_core\nipmi_msghandler" | tee /etc/modules-load.d/driver.conf

- name: pull driver build image
  command: docker pull nvcr.io/nvidia/driver:460.73.01-5.10.32-flatcar

- name: run the build
  command: docker run --rm -ti --privileged --pid=host -v /run/nvidia:/run/nvidia:shared -v /tmp/nvidia:/var/log -v /usr/lib64/modules:/usr/lib64/modules --name nvidia-driver nvcr.io/nvidia/driver:460.73.01-5.10.32-flatcar
