---
- include: install-redhat.yaml
  when: ansible_os_family == "RedHat"

- include: install-suse.yaml
  when: ansible_os_family == "Suse"

- include: install-flatcar.yaml
  when: ansible_os_family == "Flatcar"

- include: nvidia.yaml
  when:
    - gpu is defined
    - gpu.type == 'nvidia'
