---
# RPM
- name: install nvidia-container-runtime rpm package
  yum:
    name: "{{ nvidia_container_runtime_package }}"
    state: present
    disable_gpg_check: true
    update_cache: true

- name: Install GPU
  block:
    - name: Install the 'Development Tools' package group
      yum:
        name: "@Development Tools"
        update_cache: yes
        state: present
    - name: Install kernel packages
      yum:
        name:
          - kernel-devel
          - epel-release
        state: present
    - name: Install DKMS
      yum:
        name:
          - dkms
        state: present
    - name: sed
      shell: >-
        sed -i '/^GRUB_CMDLINE_LINUX=/s/"$/ module_name.blacklist=1
        rd.driver.blacklist=nouveau modprobe.blacklist=nouveau"/'
        /etc/default/grub
    - name: Remove nouveau driver
      shell: dracut --omit-drivers nouveau -f
    - name: Update GRUB
      shell: grub2-mkconfig -o /boot/grub2/grub.cfg
    - name: Reboot
      reboot:
    - name: Install packages
      yum:
        name:
          - tar
          - bzip2
          - make
          - automake
          - gcc
          - gcc-c++
          - pciutils
          - elfutils-libelf-devel
          - libglvnd-devel
          - iptables
          - firewalld
          - vim
          - bind-utils
          - wget
        state: present
    - name: Install Kernel headers
      yum:
        name:
          - kernel-devel-{{ ansible_kernel }}
          - kernel-headers-{{ ansible_kernel }}
    - name: Clean cache
      shell: yum clean expire-cache
    - name: Install NVIDIA driver (centos/rhel 7)
      yum:
        name:
          - >-
            {{ nvidia_driver_package_name }}:{{ nvidia_driver_package_version }}
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution == 'RedHat'
        - ansible_distribution_major_version|int == 7
    - name: Install NVIDIA driver (centos/rhel 8)
      dnf:
        name: >-
          @{{ nvidia_driver_module_name }}:{{ nvidia_driver_module_version }}
        state: present
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version | int >= 8
