---
- include: redhat.yaml
  when:
    - ansible_facts['os_family'] == "RedHat"
    - not offline_mode_enabled

- include: redhat-offline.yaml
  when:
    - ansible_facts['os_family'] == "RedHat"
    - offline_mode_enabled

- include: suse.yaml
  when: ansible_facts['os_family'] == "Suse"

- include: debian.yaml
  when: ansible_facts['os_family'] == "Debian"
