---
- name: Converge
  hosts: all
  tasks:
    - set_fact:
        packer_builder_type: amazon
        sysprep: true
        gpu:
          types:
            - nvidia

- name: "Include Provision"
  include: ../../provision.yaml
