---

  # Force fact gathering once the nodes have been bootstrapped
  - hosts: node control-plane
    name: "Gather Node Facts"
    gather_facts: yes
    tasks: []

  - hosts: node control-plane
    any_errors_fatal: true
    name: "Configure Cluster Prerequisites"
    become: yes
    environment: "{{ combined_env }}"

    roles:
      - prereqs
      - disable-swap
      - cloud-netconfig-manage
