---
- hosts: all
  name: Provision
  become: true
  # TODO: hack to pass vars easily for now
  pre_tasks:
    - include_vars: vars/centos/centos-7.yaml
      when: ansible_os_family == "RedHat"
    - include_vars: vars/flatcar/flatcar.yaml
      when: ansible_os_family == "Flatcar"
  roles:
    - role: packages
    - role: gpu
    - role: config
    - role: networking
    - role: providers
    - role: images
      when: download_images
    - role: sysprep
      when: sysprep # make the finalize process skipable
  environment: "{{ default_env }}"
