---
  - block:
    - name: remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    # kubelet fails even if ansible_swaptotal_mb = 0
    - name: check swap
      command: swapon -s
      register: swapon
      changed_when: no

    - name: disable swap
      command: swapoff -a
      when: swapon.stdout

    when:
      - not (spec.kubernetes.preflightChecks is defined and spec.kubernetes.preflightChecks.errorsToIgnore is defined and (('all' in spec.kubernetes.preflightChecks.errorsToIgnore) or ('swap' in spec.kubernetes.preflightChecks.errorsToIgnore)))
