---
name: GoReleaser

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Snapshot
        run: make devkit.run
        env:
          WHAT: make build.snapshot

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: mesosphereci
          password: ${{ secrets.DOCKER_PASS }}

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        run: make devkit.run
        env:
          DOCKER_CLI_EXPERIMENTAL: "enabled"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WHAT: make release
