---
"on":
  push:
    branches:
      - main
      - ae/darwin-sig

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      release_tag_name: ${{ steps.release-please.outputs.tag_name }}
      release_upload_url: ${{ steps.release-please.outputs.upload_url }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: go
          package-name: konvoy-image-builder
          changelog-types: >-
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":true}
            ]

#      - if: ${{ steps.release-please.outputs.release_created }}
      -  uses: actions/checkout@v3
        with:
          fetch-depth: 0

#      - if: ${{ steps.release-please.outputs.release_created }}
      -  name: Snapshot
        run: make devkit.run
        env:
          WHAT: make build.snapshot

#      - if: ${{ steps.release-please.outputs.release_created }}
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: mesosphereci
          password: ${{ secrets.DOCKER_PASS }}

#      - if: ${{ steps.release-please.outputs.release_created }}
      - name: Release
        run: make devkit.run
        env:
          DOCKER_CLI_EXPERIMENTAL: "enabled"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WHAT: make release

  sign-osx:
    needs: release-please
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact

      - name: Display artifacts downloaded
        run: ls -R
        working-directory: macosx-artifacts
