---
"on":
  push:
    branches:
      - main
      - ae/darwin-sig

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      release_tag_name: ${{ steps.release-please.outputs.tag_name }}
      release_upload_url: ${{ steps.release-please.outputs.upload_url }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: go
          package-name: konvoy-image-builder
          changelog-types: >-
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":true}
            ]

      - if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

  release-osx:
    needs: release-please
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install binaries via HomeBrew for code signing and app notarization and building
        run: |
          brew tap mitchellh/gon
          brew install mitchellh/gon/gon
          brew install goreleaser

#      - name: Make Snapshot
#        run: make build.snapshot

      - name: Make Release
        env:
          DOCKER_CLI_EXPERIMENTAL: "enabled"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AC_USERNAME: ${{ secrets.AC_USERNAME }}
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
          AC_APP_IDENTITY: ${{ secrets.AC_APP_IDENTITY }}
        run: make release

  bump-kib:
    needs: release-osx
    runs-on: ubuntu-latest
    steps:
      - if: ${{ needs.release-please.outputs.release_created }}
        name: Setup Go
        uses: actions/setup-go@v3
        with:
           go-version: '1.17.0'

      - if: ${{ needs.release-please.outputs.release_created }}
        name: Fetch CAPPP
        uses: actions/checkout@v3
        with:
          repository: mesosphere/cluster-api-provider-preprovisioned
          token: ${{ secrets.MESOSPHERECI_USER_TOKEN }}
          path: cluster-api-provider-preprovisioned
          fetch-depth: 0

      - if: ${{ needs.release-please.outputs.release_created }}
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - if: ${{ needs.release-please.outputs.release_created }}
        name: Update KIB in CAPPP
        run: make update-kib
        working-directory: cluster-api-provider-preprovisioned
        env:
          GITHUB_TOKEN: ${{ secrets.MESOSPHERECI_USER_TOKEN }}

      - if: ${{ needs.release-please.outputs.release_created }}
        name: Create Pull Request for KIB bump in CAPPP
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.MESOSPHERECI_USER_TOKEN }}
          add-paths: preprovisioned/kib
          body: bumps KIB to latest version
          commit: "feat: bump kib to ${{ needs.release-please.outputs.release_tag_name }}"
          path: cluster-api-provider-preprovisioned
          title: "feat: bump kib to ${{ needs.release-please.outputs.release_tag_name }}"
